"""Дополнительные модели для расширения словаря до 1000+ записей."""

ADDITIONAL_MODELS: dict[str, str] = {
    # ===== классические УЧП/ОДУ =====
    "Biharmonic equation model": "Бигармоническая модель",
    "Triharmonic equation": "Тригармоническое уравнение",
    "Monge-Ampere equation model": "Модель Monge-Ampère",
    "Calabi-Yau type equations": "Уравнения типа Calabi-Yau",
    "Mean curvature flow": "Поток средней кривизны",
    "Ricci flow model": "Модель потока Ricci",
    "Willmore flow": "Поток Willmore",
    "Curve shortening flow": "Поток укорочения кривой",
    "Anisotropic diffusion model": "Анизотропная диффузия",
    "Nonlinear diffusion model": "Нелинейная диффузия",
    "Porous medium equation": "Уравнение пористой среды",
    "Fast diffusion equation": "Уравнение быстрой диффузии",
    "Slow diffusion equation": "Уравнение медленной диффузии",
    "Douglas-Rachford splitting model": "Модель Douglas-Rachford",
    "Splitting methods model": "Модель операторного splitting",
    "Level set transport equation": "Транспорт level-set",
    "Hamilton-Jacobi-Bellman-Isaacs": "HJB-Isaacs уравнение",
    "Isaacs equation": "Уравнение Isaacs",
    "Eikonal equation model": "Eikonal-модель",
    "Geometric optics model": "Модель геометрической оптики",
    "Paraxial wave equation": "Параксиальное волновое уравнение",
    "Nonlinear wave equation": "Нелинейное волновое уравнение",
    "Klein-Gordon model": "Модель Klein-Gordon",
    "Sine-Gordon model": "Модель sine-Gordon",
    "Nonlinear elasticity model": "Нелинейная упругость",
    "Saint Venant-Kirchhoff model": "Модель Saint Venant-Kirchhoff",
    "Neo-Hookean model": "Модель Neo-Hookean",
    "Mooney-Rivlin model": "Модель Mooney-Rivlin",
    "Ogden hyperelastic model": "Гиперупругая модель Ogden",
    "Gent model": "Модель Gent",
    "Arruda-Boyce model": "Модель Arruda-Boyce",
    "Yeoh model": "Модель Yeoh",
    "Fung exponential model": "Экспоненциальная модель Fung",
    "Holzapfel-Gasser-Ogden model": "Модель Holzapfel-Gasser-Ogden",
    "Anisotropic hyperelasticity": "Анизотропная гиперупругость",
    "Fiber-reinforced model": "Модель с волоконным армированием",
    "Soft tissue model": "Модель мягких тканей",
    "Corneal biomechanics model": "Биомеханика роговицы",
    "Aortic wall model": "Модель стенки аорты",
    "Cardiac electromechanics": "Электромеханика сердца",
    "Bidomain model": "Bidomain-модель",
    "Monodomain model": "Monodomain-модель",
    "Aliev-Panfilov model": "Модель Aliev-Panfilov",
    "Bueno-Orovio model": "Модель Bueno-Orovio",
    "Ten Tusscher model": "Модель ten Tusscher",
    "Luo-Rudy model": "Модель Luo-Rudy",
    "Courtemanche model": "Модель Courtemanche",
    "Mitchell-Schaeffer model": "Модель Mitchell-Schaeffer",
    "Purkinje fiber model": "Модель волокон Пуркинje",
    "Atrial fibrillation model": "Модель фибрилляции предсердий",
    "Ventricular arrhythmia model": "Модель желудочковой аритмии",
    "Coronary circulation model": "Модель коронарного кровообращения",
    "Lumped parameter cardiovascular model": "Сосредоточенная сердечно-сосудистая модель",
    "0D cardiovascular model": "0D сердечно-сосудистая модель",
    "1D arterial network model": "1D модель артериальной сети",
    "3D heart fluid-structure model": "3D модель сердца FSI",
    "Lung mechanics model": "Модель механики лёгких",
    "Respiratory gas exchange model": "Модель газообмена в лёгких",
    "Alveolar-capillary model": "Альвеолярно-капиллярная модель",
    "Dialysis transport model": "Модель транспорта при диализе",
    "Pharmacokinetics model": "Фармакокинетическая модель",
    "Pharmacodynamics model": "Фармакодинамическая модель",
    "PBPK model": "PBPK-модель",
    "Tissue perfusion model": "Модель перфузии тканей",
    "Drug delivery model": "Модель доставки лекарств",
    "Wound healing model": "Модель заживления ран",
    "Bone remodeling model": "Модель ремоделирования кости",
    "Mechanobiology model": "Механобиологическая модель",
    "Cell migration model": "Модель миграции клеток",
    "Chemotaxis-Keller-Segel": "Модель Keller-Segel",
    "Volume-filling chemotaxis": "Хemotaxis с заполнением объёма",
    "Patlak-Keller model": "Модель Patlak-Keller",
    "Angiogenesis network model": "Сетевая модель ангиогенеза",
    "Vascular tumor model": "Сосудистая модель опухоли",
    "Immune response model": "Модель иммунного ответа",
    "Virus dynamics model": "Модель динамики вируса",
    "Epidemic SIRS model": "SIRS-эпидемиологическая модель",
    "SEIRS model": "SEIRS-модель",
    "Agent epidemic model": "Агентная эпидемиологическая модель",
    "Metapopulation epidemic model": "Метапопуляционная эпидемиологическая модель",
    # ===== горение / реакции =====
    "Premixed flame model": "Модель предварительно смешанного пламени",
    "Diffusion flame model": "Модель диффузионного пламени",
    "Counterflow flame model": "Модель противотокового пламени",
    "Turbulent combustion model": "Модель турбulentного горения",
    "Flamelet model": "Flamelet-модель",
    "G-equation combustion model": "G-уравнение горения",
    "Level-set combustion model": "Level-set модель горения",
    "Eddy dissipation model": "Модель дissipation завихрений",
    "Eddy dissipation concept": "Концепция dissipation завихрений",
    "Partially stirred reactor model": "Модель частично перемешанного реактора",
    "PaSR combustion model": "PaSR-модель горения",
    "Conditional moment closure": "Conditional moment closure",
    "Probability density function combustion": "PDF-модель горения",
    "Laminar flame speed model": "Модель скорости ламинарного пламени",
    "Ignition delay model": "Модель задержки воспламенения",
    "Detonation model": "Модель детонации",
    "Deflagration-to-detonation model": "Модель перехода деflagration-detonation",
    "Shock tube model": "Модель ударной трубы",
    "Explosion dynamics model": "Модель динамики взрыва",
    "Coal combustion model": "Модель сжигания угля",
    "Biomass pyrolysis model": "Модель пиролиза биомассы",
    "Gasification model": "Модель газификации",
    "Syngas reactor model": "Модель реактора синтез-газа",
    "Fischer-Tropsch reactor model": "Модель реактора Fischer-Tropsch",
    "Steam reforming model": "Модель парового риформинга",
    "Water-gas shift model": "Модель реакции water-gas shift",
    "Methanol synthesis model": "Модель синтеза метanol",
    "Ammonia synthesis model": "Модель синтеза аммиака",
    "Haber-Bosch reactor model": "Модель реактора Haber-Bosch",
    "Catalytic converter model": "Модель каталитического нейтрализатора",
    "Three-way catalyst model": "Модель трёхкомпонентного катализатора",
    "SCR denitrification model": "SCR-модель денitrification",
    "Electrolyzer model": "Модель электролизёра",
    "Fuel cell PEM model": "PEM-топливный элемент",
    "Solid oxide fuel cell model": "SOFC-модель",
    "Molten carbonate fuel cell model": "MCFC-модель",
    "Battery electrochemical model": "Электрохимическая модель батареи",
    "Single particle battery model": "Модель одиночной частицы батареи",
    "P2D battery model": "P2D-модель батареи",
    "Thermal runaway battery model": "Модель теплового разгона батареи",
    "Lithium plating model": "Модель Li-plating",
    "SEI growth model": "Модель роста SEI",
    "Capacity fade model": "Модель дegradation ёмкости",
    "Supercapacitor model": "Модель суперконденсатора",
    "Redox flow battery model": "Модель redox flow батареи",
    # ===== климат / океан / атмосфера =====
    "Primitive equation ocean model": "Примитивные уравнения океана",
    "Shallow water ocean model": "Мелководная модель океана",
    "Barotropic ocean model": "Баротропная модель океана",
    "Baroclinic ocean model": "Бароклинная модель океана",
    "Thermohaline circulation model": "Модель термohaline circulation",
    "Meridional overturning model": "Модель meridional overturning",
    "Ekman transport model": "Модель Ekman-транспорта",
    "Coriolis circulation model": "Модель кориолисовой циркуляции",
    "Geostrophic balance model": "Модель geostrophic balance",
    "Quasi-geostrophic model": "Quasi-geostrophic модель",
    "Potential vorticity model": "Модель потенциальной vorticity",
    "Rossby wave model": "Модель Rossby-волн",
    "Kelvin wave model": "Модель Kelvin-волн",
    "Internal wave model": "Модель internal waves",
    "Tsunami propagation model": "Модель распространения цунами",
    "Storm surge model": "Модель storm surge",
    "Coastal hydrodynamics model": "Модель прибрежной гидродинамики",
    "Estuary circulation model": "Модель estuary circulation",
    "Sediment transport model": "Модель переноса sediment",
    "Morphodynamics model": "Морфодинамическая модель",
    "River meandering model": "Модель извилин реки",
    "Dam break model": "Модель прорыва плотины",
    "Reservoir simulation model": "Модель симуляции reservoir",
    "Aquifer flow model": "Модель потока aquifer",
    "Groundwater contamination model": "Модель загрязнения groundwater",
    "Atmospheric boundary layer model": "Модель атмосферного пограничного слоя",
    "Mesoscale meteorology model": "Mesoscale метеорологическая модель",
    "Large eddy atmospheric model": "LES-модель атмосферы",
    "Cloud microphysics model": "Модель cloud microphysics",
    "Warm rain model": "Модель warm rain",
    "Ice microphysics model": "Модель ледяной microphysics",
    "Radiation-convection model": "Radiation-convection модель",
    "General circulation model": "Модель general circulation",
    "Energy balance climate model": "Energy balance климатическая модель",
    "Box climate model": "Box-модель климата",
    "Carbon cycle model": "Модель углеродного цикла",
    "Land surface model": "Модель land surface",
    "Vegetation dynamics model": "Модель динамики растительности",
    "Wildfire spread model": "Модель распространения wildfire",
    "Smoke transport model": "Модель переноса дыма",
    "Air quality dispersion model": "Модель рассеяния загрязнения воздуха",
    "Gaussian plume model": "Gaussian plume модель",
    "Urban canopy model": "Urban canopy модель",
    "Building aerodynamics model": "Аэродинамика зданий",
    "Wind turbine wake model": "Модель wake ветрoturbine",
    "Offshore wind farm model": "Модель offshore wind farm",
    "Solar irradiance model": "Модель solar irradiance",
    "Photovoltaic performance model": "Модель PV-производительности",
    # ===== структурная / геомеханика =====
    "Beam bending model": "Модель изгиба балки",
    "Euler-Bernoulli beam model": "Модель балки Euler-Bernoulli",
    "Timoshenko beam model": "Модель балки Timoshenko",
    "Plate bending model": "Модель изгиба пластины",
    "Kirchhoff plate model": "Модель пластины Kirchhoff",
    "Mindlin plate model": "Модель пластины Mindlin",
    "Shell theory model": "Оболочечная модель",
    "Koiter shell model": "Модель оболочки Koiter",
    "Sandwich panel model": "Модель sandwich-панели",
    "Composite laminate model": "Модель composite laminate",
    "Classical laminate theory": "Classical laminate theory",
    "First-order shear deformation": "First-order shear deformation",
    "Delamination model": "Модель delamination",
    "Interlaminar stress model": "Модель interlaminar stress",
    "Progressive damage model": "Модель progressive damage",
    "Hashin failure criterion": "Критерий Hashin",
    "Tsai-Wu failure criterion": "Критерий Tsai-Wu",
    "Puck failure model": "Модель Puck failure",
    "Virtual crack closure model": "Virtual crack closure model",
    "Extended finite element model": "Extended FEM модель",
    "XFEM fracture model": "XFEM-модель разрушения",
    "Peridynamic fracture model": "Peridynamic модель разрушения",
    "Phase-field fatigue model": "Phase-field модель усталости",
    "Paris-Erdogan law model": "Модель Paris-Erdogan",
    "Crack propagation model": "Модель распространения трещины",
    "Dynamic fracture model": "Динамическая модель разрушения",
    "Rock mechanics model": "Модель rock mechanics",
    "Hoek-Brown criterion": "Критерий Hoek-Brown",
    "Drucker-Prager cap model": "Drucker-Prager cap модель",
    "Cam clay plasticity model": "Cam clay пластичность",
    "Modified Cam clay model": "Modified Cam clay модель",
    "Critical state soil model": "Critical state soil модель",
    "Lade-Duncan model": "Модель Lade-Duncan",
    "MCC soil consolidation model": "MCC consolidation модель",
    "Biots poroelastic wave model": "Poroelastic wave модель Biot",
    "Wave propagation in porous media": "Распространение волн в пористой среде",
    "Tunnel excavation model": "Модель tunnel excavation",
    "Slope stability model": "Модель slope stability",
    "Retaining wall model": "Модель подпорной стенки",
    "Foundation settlement model": "Модель осадки foundation",
    "Pile-soil interaction model": "Модель pile-soil interaction",
    "Earthquake ground motion model": "Модель сейсmic ground motion",
    "Site response model": "Site response модель",
    "Soil-structure interaction model": "Soil-structure interaction модель",
    "Base isolation model": "Модель base isolation",
    "Tuned mass damper model": "Tuned mass damper модель",
    "Structural health monitoring model": "SHM-модель",
    "Damage detection inverse model": "Обратная модель damage detection",
    # ===== электромагнетизм / оптика =====
    "Maxwell eigenmode model": "Maxwell eigenmode модель",
    "Waveguide propagation model": "Модель waveguide propagation",
    "Photonic crystal model": "Модель photonic crystal",
    "Plasmonics model": "Plasmonics-модель",
    "Surface plasmon model": "Surface plasmon модель",
    "Metamaterial model": "Metamaterial-модель",
    "Negative index material model": "Negative index material модель",
    "Electromagnetic scattering model": "EM scattering модель",
    "RCS prediction model": "RCS prediction модель",
    "Antenna radiation model": "Antenna radiation модель",
    "Radar propagation model": "Radar propagation модель",
    "Ionospheric propagation model": "Ionospheric propagation модель",
    "Optical fiber model": "Optical fiber модель",
    "Nonlinear optics model": "Nonlinear optics модель",
    "Kerr effect model": "Kerr effect модель",
    "Four-wave mixing model": "Four-wave mixing модель",
    "Laser cavity model": "Laser cavity модель",
    "Rate equation laser model": "Rate equation laser модель",
    "Semiconductor laser model": "Semiconductor laser модель",
    "Quantum dot laser model": "Quantum dot laser модель",
    "LED efficiency model": "LED efficiency модель",
    "Photodetector model": "Photodetector модель",
    "Solar cell drift-diffusion model": "Drift-diffusion модель solar cell",
    "Organic photovoltaic model": "Organic PV модель",
    "Perovskite solar cell model": "Perovskite solar cell модель",
    "Thermophotovoltaic model": "Thermophotovoltaic модель",
    "Blackbody radiation model": "Blackbody radiation модель",
    "Planck radiation model": "Planck radiation модель",
    "Radiative heat transfer model": "Radiative heat transfer модель",
    "Participating media radiation model": "Participating media radiation модель",
    "DOM radiation model": "DOM radiation модель",
    "Monte Carlo radiation model": "Monte Carlo radiation модель",
    # ===== ядерная / плазма =====
    "Tokamak equilibrium model": "Tokamak equilibrium модель",
    "Grad-Shafranov equation model": "Grad-Shafranov модель",
    "MHD equilibrium model": "MHD equilibrium модель",
    "Plasma turbulence model": "Plasma turbulence модель",
    "Gyrokinetic model": "Gyrokinetic модель",
    "Particle-in-cell model": "Particle-in-cell модель",
    "Vlasov-PIC hybrid model": "Vlasov-PIC hybrid модель",
    "Magnetic reconnection model": "Magnetic reconnection модель",
    "Solar wind model": "Solar wind модель",
    "Magnetosphere model": "Magnetosphere модель",
    "Space weather model": "Space weather модель",
    "Radiation belt model": "Radiation belt модель",
    "Neutron transport SN model": "Neutron transport SN модель",
    "Criticality safety model": "Criticality safety модель",
    "Reactor kinetics model": "Reactor kinetics модель",
    "Fuel depletion model": "Fuel depletion модель",
    "Decay heat model": "Decay heat модель",
    "Fission product release model": "Fission product release модель",
    "Containment thermal model": "Containment thermal модель",
    # ===== численные методы как модели =====
    "Finite volume method model": "Метод конечных объёмов",
    "Discontinuous Galerkin model": "Discontinuous Galerkin модель",
    "Spectral element model": "Spectral element модель",
    "Isogeometric analysis model": "Isogeometric analysis модель",
    "Meshless method model": "Meshless метод",
    "Radial basis function model": "Radial basis function модель",
    "Collocation method model": "Collocation метод",
    "Pseudospectral method model": "Pseudospectral метод",
    "Multigrid solver model": "Multigrid solver модель",
    "Preconditioned Krylov model": "Preconditioned Krylov модель",
    "Domain decomposition model": "Domain decomposition модель",
    "Adaptive mesh refinement model": "Adaptive mesh refinement модель",
    "Immersed finite element model": "Immersed FEM модель",
    "Cut-cell method model": "Cut-cell метод",
    "Material point method model": "Material point method",
    "Lattice spring model": "Lattice spring модель",
    "Bond-based peridynamics model": "Bond-based peridynamics",
    "State-based peridynamics model": "State-based peridynamics",
    "Coupled Eulerian-Lagrangian model": "Coupled Eulerian-Lagrangian модель",
    "Arbitrary Lagrangian-Eulerian model": "Arbitrary Lagrangian-Eulerian модель",
    "Operator splitting model": "Operator splitting модель",
    "Fractional step method model": "Fractional step метод",
    "Projection method Navier-Stokes": "Projection метод Navier-Stokes",
    "Artificial compressibility model": "Artificial compressibility модель",
    "Penalty method model": "Penalty method модель",
    "Augmented Lagrangian model": "Augmented Lagrangian модель",
    "Adjoint-based optimization model": "Adjoint-based optimization модель",
    "Sensitivity analysis model": "Sensitivity analysis модель",
    "Uncertainty quantification model": "Uncertainty quantification модель",
    "Bayesian calibration model": "Bayesian calibration модель",
    "Markov chain Monte Carlo inversion": "MCMC inversion модель",
    "Ensemble Kalman inversion model": "Ensemble Kalman inversion модель",
    "4D-Var assimilation model": "4D-Var assimilation модель",
    "3D-Var assimilation model": "3D-Var assimilation модель",
    "Hybrid assimilation model": "Hybrid assimilation модель",
    "Neural operator surrogate model": "Neural operator surrogate",
    "Physics-constrained ML model": "Physics-constrained ML модель",
    "Symbolic regression model": "Symbolic regression модель",
    "Equation discovery model": "Equation discovery модель",
    "Sparse identification model": "Sparse identification модель",
    "SINDy model": "SINDy-модель",
    "Deep Ritz method model": "Deep Ritz method модель",
    "Weak adversarial network model": "Weak adversarial network модель",
    "Variational autoencoder surrogate": "VAE surrogate модель",
    "Generative design model": "Generative design модель",
    "Multi-objective optimization model": "Multi-objective optimization модель",
    "Pareto front exploration model": "Pareto front exploration модель",
    "Robust optimization model": "Robust optimization модель",
    "Chance-constrained optimization model": "Chance-constrained optimization модель",
    "Stochastic programming model": "Stochastic programming модель",
    "Dynamic programming model": "Dynamic programming модель",
    "Model predictive control model": "Model predictive control модель",
    "Nonlinear MPC model": "Nonlinear MPC модель",
    "Distributed parameter control model": "Distributed parameter control модель",
    "Boundary control model": "Boundary control модель",
    "Observer design model": "Observer design модель",
    "Luenberger observer model": "Luenberger observer модель",
    "Sliding mode observer model": "Sliding mode observer модель",
    "H-infinity control model": "H-infinity control модель",
    "LQR control model": "LQR control модель",
    "LQG control model": "LQG control модель",
    "Passivity-based control model": "Passivity-based control модель",
    "Backstepping control model": "Backstepping control модель",
    "Feedback linearization model": "Feedback linearization модель",
    "Flatness-based control model": "Flatness-based control модель",
    "Port-Hamiltonian model": "Port-Hamiltonian модель",
    "Bond graph model": "Bond graph модель",
    "Network thermodynamics model": "Network thermodynamics модель",
    "Exergy analysis model": "Exergy analysis модель",
    "Pinch analysis model": "Pinch analysis модель",
    "Heat integration model": "Heat integration модель",
    "Process synthesis model": "Process synthesis модель",
    "Mass integration model": "Mass integration модель",
    "Life cycle assessment model": "Life cycle assessment модель",
    "Technoeconomic model": "Technoeconomic модель",
    "Supply chain optimization model": "Supply chain optimization модель",
    "Logistics network model": "Logistics network модель",
    "Traffic flow LWR model": "LWR traffic flow модель",
    "Aw-Rascle traffic model": "Aw-Rascle traffic модель",
    "Cell transmission model": "Cell transmission модель",
    "Pedestrian dynamics model": "Pedestrian dynamics модель",
    "Crowd evacuation model": "Crowd evacuation модель",
    "Social force model": "Social force модель",
    "Opinion dynamics model": "Opinion dynamics модель",
    "Voter model": "Voter модель",
    "Sznajd model": "Sznajd модель",
    "Deffuant model": "Deffuant модель",
    "Hegselmann-Krause model": "Hegselmann-Krause модель",
    "Game theory evolutionary model": "Evolutionary game theory модель",
    "Replicator dynamics model": "Replicator dynamics модель",
    "Resource competition model": "Resource competition модель",
    "Predator-prey model": "Predator-prey модель",
    "Competitive Lotka-Volterra model": "Competitive Lotka-Volterra модель",
    "Food web model": "Food web модель",
    "Ecosystem nutrient cycle model": "Ecosystem nutrient cycle модель",
    "Lake eutrophication model": "Lake eutrophication модель",
    "Algal bloom model": "Algal bloom модель",
    "Fisheries stock model": "Fisheries stock модель",
    "Harvesting optimization model": "Harvesting optimization модель",
    "Forest fire spread model": "Forest fire spread модель",
    "Drought propagation model": "Drought propagation модель",
    "Crop growth model": "Crop growth модель",
    "Agro-hydrological model": "Agro-hydrological модель",
    "Irrigation scheduling model": "Irrigation scheduling модель",
    "Precision agriculture model": "Precision agriculture модель",
    # ===== дополнение до 1000+ в облаке =====
    "Acoustic emission model": "Модель акустической эмиссии",
    "Ultrasonic wave model": "Модель ультразвуковых волн",
    "Piezoelectric harvester model": "Модель пьезoэлектрического генератора",
    "Thermoacoustic engine model": "Модель терmoacoustic engine",
    "Stirling engine model": "Модель Stirling engine",
    "Rankine cycle model": "Модель Rankine cycle",
    "Brayton cycle model": "Модель Brayton cycle",
    "Otto cycle model": "Модель Otto cycle",
    "Diesel cycle model": "Модель Diesel cycle",
    "Heat pump cycle model": "Модель heat pump cycle",
    "Refrigeration cycle model": "Модель refrigeration cycle",
    "Absorption chiller model": "Модель absorption chiller",
    "Desalination RO model": "Модель обратного osmosis",
    "Membrane separation model": "Модель membrane separation",
    "Ultrafiltration model": "Модель ultrafiltration",
    "Nanofiltration model": "Модель nanofiltration",
    "Electrodialysis model": "Модель electrodialysis",
    "Capillary electrophoresis model": "Модель capillary electrophoresis",
    "Microfluidic chip model": "Модель microfluidic chip",
    "Lab-on-a-chip model": "Модель lab-on-a-chip",
    "Droplet microfluidics model": "Модель droplet microfluidics",
    "Inkjet printing model": "Модель inkjet printing",
    "Additive manufacturing heat model": "Тепловая модель 3D-печати",
    "Selective laser melting model": "Модель selective laser melting",
    "Powder bed fusion model": "Модель powder bed fusion",
    "Directed energy deposition model": "Модель directed energy deposition",
    "Welding heat transfer model": "Модель теплообмена при сварке",
    "Arc welding pool model": "Модель сварочной ванны",
    "Laser welding model": "Модель laser welding",
    "Friction stir welding model": "Модель friction stir welding",
    "Corrosion electrochemistry model": "Модель corrosion electrochemistry",
    "Pitting corrosion model": "Модель pitting corrosion",
    "Galvanic corrosion model": "Модель galvanic corrosion",
    "Stress corrosion cracking model": "Модель stress corrosion cracking",
    "Hydrogen embrittlement model": "Модель hydrogen embrittlement",
    "Creep rupture model": "Модель creep rupture",
    "Thermal fatigue model": "Модель thermal fatigue",
    "Thermo-mechanical fatigue model": "Модель thermo-mechanical fatigue",
    "Low cycle fatigue model": "Модель low cycle fatigue",
    "High cycle fatigue model": "Модель high cycle fatigue",
    "Vibration fatigue model": "Модель vibration fatigue",
    "Rotor dynamics model": "Модель rotor dynamics",
    "Gas turbine blade model": "Модель gas turbine blade",
    "Steam turbine model": "Модель steam turbine",
    "Compressor aerodynamics model": "Модель compressor aerodynamics",
    "Centrifugal pump model": "Модель centrifugal pump",
    "Axial fan model": "Модель axial fan",
    "Hydraulic turbine model": "Модель hydraulic turbine",
    "Bearings lubrication model": "Модель bearings lubrication",
    "EHD lubrication model": "Модель EHD lubrication",
    "Tribology contact model": "Модель tribology contact",
    "Surface roughness model": "Модель surface roughness",
    "Wear prediction model": "Модель wear prediction",
    "Cavitation erosion model": "Модель cavitation erosion",
    "Hydraulic transients model": "Модель hydraulic transients",
    "Water hammer model": "Модель water hammer",
    "Pipeline leak detection model": "Модель pipeline leak detection",
    "Reservoir pressure model": "Модель reservoir pressure",
    "Wellbore flow model": "Модель wellbore flow",
    "Hydraulic fracturing model": "Модель hydraulic fracturing",
    "Enhanced oil recovery model": "Модель enhanced oil recovery",
    "Carbon sequestration model": "Модель carbon sequestration",
    "Geothermal reservoir model": "Модель geothermal reservoir",
    "Magma dynamics model": "Модель magma dynamics",
    "Volcano eruption model": "Модель volcano eruption",
    "Lava flow model": "Модель lava flow",
    "Tectonic plate model": "Модель tectonic plate",
    "Fault slip model": "Модель fault slip",
    "Induced seismicity model": "Модель induced seismicity",
    "Geomechanical compaction model": "Модель geomechanical compaction",
    "Salt dome model": "Модель salt dome",
    "Caprock integrity model": "Модель caprock integrity",
    "Methane hydrate model": "Модель methane hydrate",
    "Permafrost thaw model": "Модель permafrost thaw",
    "Arctic ice melt model": "Модель arctic ice melt",
    "Glacier calving model": "Модель glacier calving",
    "Ice shelf model": "Модель ice shelf",
    "Snowpack model": "Модель snowpack",
    "Avalanche dynamics model": "Модель avalanche dynamics",
    "Debris flow model": "Модель debris flow",
    "Landslide runout model": "Модель landslide runout",
    "Rockfall trajectory model": "Модель rockfall trajectory",
}
