"""Generate translation_dict.py with a single direct LABEL_RU mapping."""

from __future__ import annotations

import re
import textwrap
from pathlib import Path

from additional_models import ADDITIONAL_MODELS

OUT = Path(__file__).with_name("translation_dict.py")

# --- все метки из context.txt (404) + 200 дополнительных моделей ---
LABEL_ENTRIES: dict[str, str] = {
    # ===== context.txt: непрерывные / алгебра =====
    "Алгебраические уравнения — AE": "Алгебраические уравнения",
    "Линейные": "Линейные уравнения",
    "Нелинейные": "Нелинейные уравнения",
    "A x = b": "A x = b",
    "F(x) = 0": "F(x) = 0",
    "Системы алгебраических уравнений": "Системы алгебраических уравнений",
    "Уравнения состояния": "Уравнения состояния",
    "Ideal Gas": "Идеальный газ",
    "Van der Waals": "Уравнение Ван-дер-Ваальса",
    "Peng–Robinson": "Уравнение Пенга-Робинсона",
    "Peng-Robinson": "Уравнение Пенга-Робинсона",
    "другие EOS": "Другие уравнения состояния",
    "Уравнения равновесия": "Уравнения равновесия",
    "Chemical equilibrium": "Химическое равновесие",
    "Phase equilibrium": "Фазовое равновесие",
    "Adsorption equilibrium": "Равновесие адсорбции",
    "Thermodynamic equilibrium": "Термодинамическое равновесие",
    "Constraint equations": "Уравнения ограничений",
    "g(x) = 0": "g(x) = 0",
    "h(x) ≤ 0": "h(x) ≤ 0",
    "g(x)=0": "g(x) = 0",
    "h(x)≤0": "h(x) ≤ 0",
    "Complementarity problems": "Задачи дополнительности",
    "g ≥ 0": "g ≥ 0",
    "λ ≥ 0": "λ ≥ 0",
    "gλ = 0": "gλ = 0",
    # ===== ODE / PDE / DAE / DDE =====
    "Дифференциальные уравнения": "Дифференциальные уравнения",
    "ODE": "ОДУ",
    "Ordinary Differential Equations": "ОДУ",
    "1-го порядка": "ОДУ первого порядка",
    "dy/dt = f(y,t)": "dy/dt = f(y,t)",
    "Высших порядков": "ОДУ высших порядков",
    "dⁿy/dtⁿ = f(...)": "dⁿy/dtⁿ = f(...)",
    "Системы ODE": "Системы ОДУ",
    "dx/dt = F(x,t)": "dx/dt = F(x,t)",
    "Автономные": "Автономные системы",
    "Неавтономные": "Неавтономные системы",
    "Chemical kinetics": "Химическая кинетика",
    "Reaction networks": "Реакционные сети",
    "Lumped thermal models": "Сосредоточенные тепловые модели",
    "Point mechanics": "Механика материальной точки",
    "Oscillators": "Осцилляторы",
    "RLC circuits": "RLC-цепи",
    "Population dynamics": "Динамика популяций",
    "Reactor dynamics": "Динамика реакторов",
    "PDE": "УЧП",
    "Partial Differential Equations": "УЧП",
    "По математическому типу": "Классификация УЧП",
    "Эллиптические": "Эллиптические УЧП",
    "Laplace": "Уравнение Лапласа",
    "Δu = 0": "Δu = 0",
    "Poisson": "Уравнение Пуассона",
    "-Δu = f": "-Δu = f",
    "Electrostatics": "Электростатика",
    "Stationary heat transfer": "Стационарный теплообмен",
    "Stationary diffusion": "Стационарная диффузия",
    "Potential flow": "Потенциальное течение",
    "Elastic equilibrium": "Упругое равновесие",
    "Параболические": "Параболические УЧП",
    "Heat equation": "Уравнение теплопроводности",
    "Diffusion equation": "Уравнение диффузии",
    "Reaction–diffusion": "Реакция-диффузия",
    "Reaction-diffusion": "Реакция-диффузия",
    "Advection–diffusion": "Адвекция-диффузия",
    "Advection-diffusion": "Адвекция-диффузия",
    "Heat conduction": "Теплопроводность",
    "Mass diffusion": "Молекулярная диффузия",
    "Species transport": "Перенос компонент",
    "Electrochemical transport": "Электрохимический перенос",
    "Porous transport": "Перенос в пористых средах",
    "Гиперболические": "Гиперболические УЧП",
    "Wave equation": "Волновое уравнение",
    "Conservation laws": "Законы сохранения",
    "Euler equations": "Уравнения Эйлера",
    "Acoustic waves": "Акустические волны",
    "Elastic waves": "Упругие волны",
    "Seismic waves": "Сейсмические волны",
    "Shock waves": "Ударные волны",
    "Compressible flow": "Сжимаемое течение",
    "Смешанного типа": "УЧП смешанного типа",
    "Tricomi-type equations": "Уравнения типа Трикоми",
    "Transonic flow": "Дозвуковое течение",
    "PDE первого порядка": "УЧП первого порядка",
    "Transport equation": "Уравнение переноса",
    "Advection equation": "Уравнение адвекции",
    "Hamilton–Jacobi": "Уравнение Гамильтона-Якоби",
    "Hamilton-Jacobi": "Уравнение Гамильтона-Якоби",
    "Системы PDE": "Системы УЧП",
    "Navier–Stokes": "Навье-Стокс",
    "Navier-Stokes": "Навье-Стокс",
    "Euler": "Уравнения Эйлера",
    "Maxwell": "Уравнения Максвелла",
    "Elasticity": "Упругость",
    "MHD": "МГД",
    "Multiphysics systems": "Мультифизические системы",
    "DAE": "ДАУ",
    "Differential-Algebraic Equations": "ДАУ",
    "ẋ = f(x,z,t)": "ẋ = f(x,z,t)",
    "0 = g(x,z,t)": "0 = g(x,z,t)",
    "Index-1 DAE": "ДАУ индекса 1",
    "Index-2 DAE": "ДАУ индекса 2",
    "Index-3+ DAE": "ДАУ индекса 3+",
    "Constrained mechanics": "Механика с ограничениями",
    "Multibody systems": "Мультителные системы",
    "Electrical networks": "Электрические сети",
    "Power systems": "Энергосистемы",
    "Chemical process simulation": "Моделирование химпроцессов",
    "Thermodynamic systems": "Термодинамические системы",
    "DDE": "ДДУ",
    "Delay Differential Equations": "ДДУ",
    "Constant delay": "Постоянная задержка",
    "ẋ(t)=f(x(t),x(t-τ))": "ẋ(t)=f(x(t),x(t-τ))",
    "Variable delay": "Переменная задержка",
    "Distributed delay": "Распределённая задержка",
    "Delayed reactions": "Запаздывающие реакции",
    "Feedback systems": "Системы с обратной связью",
    "Biological regulation": "Биологическая регуляция",
    "Transport delays": "Задержки переноса",
    "Functional Differential Equations": "Функционально-дифференциальные уравнения",
    "состояние зависит от функции истории": "Уравнения с функциональной историей",
    "Fractional Differential Equations": "Дробные дифференциальные уравнения",
    "Fractional ODE": "Дробные ОДУ",
    "Fractional PDE": "Дробные УЧП",
    "Caputo derivatives": "Производные Капуто",
    "Riemann–Liouville derivatives": "Производные Римана-Лиувилля",
    "Riemann-Liouville derivatives": "Производные Римана-Лиувилля",
    "Anomalous diffusion": "Аномальная диффузия",
    "Viscoelasticity": "Вязкоупругость",
    "Polymer dynamics": "Динамика полимеров",
    "Systems with memory": "Системы с памятью",
    "Differential Inclusions": "Дифференциальные включения",
    "ẋ ∈ F(x)": "ẋ ∈ F(x)",
    "Dry friction": "Сухое трение",
    "Contact": "Контакт",
    "Plasticity": "Пластичность",
    "Hysteresis": "Гистерезис",
    "Nonsmooth mechanics": "Негладкая механика",
    # ===== интегральные / IDE / память =====
    "Интегральные уравнения": "Интегральные уравнения",
    "Fredholm": "Уравнения Фредгольма",
    "Volterra": "Уравнения Вольтерра",
    "I рода": "Интегральные уравнения I рода",
    "II рода": "Интегральные уравнения II рода",
    "Singular integral equations": "Сингулярные интегральные уравнения",
    "Boundary integral equations": "Граничные интегральные уравнения",
    "Potential theory": "Теория потенциала",
    "Electromagnetism": "Электродинамика",
    "Wave scattering": "Рассеяние волн",
    "Radiation": "Излучение",
    "Fracture mechanics": "Механика разрушения",
    "BEM formulations": "Граничные интегральные формулировки",
    "Интегро-дифференциальные уравнения — IDE": "ИДУ",
    "ODE + integral operator": "ИДУ",
    "PDE + integral operator": "ИДУ",
    "Nonlocal mechanics": "Нелокальная механика",
    "Radiation transport": "Перенос излучения",
    "Kinetic theory": "Кинетическая теория",
    "Long-range interactions": "Дальнодействующие взаимодействия",
    "Уравнения с памятью": "Уравнения с памятью",
    "Hereditary equations": "Наследственные уравнения",
    "Memory kernels": "Ядра памяти",
    "Convolution models": "Сверточные модели",
    "Creep": "Ползучесть",
    "Relaxation": "Релаксация",
    "Polymers": "Полимеры",
    "Biological tissues": "Биологические ткани",
    # ===== дискретные =====
    "ДИСКРЕТНЫЕ МОДЕЛИ": "Дискретные модели",
    "Difference Equations": "Разностные уравнения",
    "xₙ₊₁ = F(xₙ)": "xₙ₊₁ = F(xₙ)",
    "Discrete dynamical systems": "Дискретные динамические системы",
    "Recurrence Relations": "Рекуррентные соотношения",
    "xₙ₊₁ = F(xₙ,xₙ₋₁,...)": "xₙ₊₁ = F(xₙ,xₙ₋₁,...)",
    "Lattice Models": "Решеточные модели",
    "Lattice models": "Решеточные модели",
    "Ising": "Модель Изинга",
    "Potts": "Модель Поттса",
    "Lattice gas": "Решеточный газ",
    "Lattice reaction models": "Решеточные реакционные модели",
    "Lattice Boltzmann": "Решеточные уравнения Больцмана",
    "Cellular Automata": "Клеточные автоматы",
    "Grain growth": "Рост зёрен",
    "Recrystallization": "Рекристаллизация",
    "Solidification": "Кристаллизация",
    "Reaction fronts": "Фронты реакции",
    "Phase evolution": "Эволюция фаз",
    "Discrete Network Models": "Дискретные сетевые модели",
    "Pore networks": "Поровые сети",
    "Thermal networks": "Тепловые сети",
    # ===== стохастические =====
    "СТОХАСТИЧЕСКИЕ МОДЕЛИ": "Стохастические модели",
    "SDE": "СДУ",
    "Stochastic Differential Equations": "СДУ",
    "Itô SDE": "СДУ Ито",
    "Stratonovich SDE": "СДУ Строновича",
    "Langevin equations": "Уравнения Ланжевена",
    "Brownian motion": "Броуновское движение",
    "Thermal fluctuations": "Тепловые флуктуации",
    "Molecular motion": "Молекулярное движение",
    "Stochastic kinetics": "Стохастическая кинетика",
    "Nucleation": "Нуклеация",
    "SPDE": "СУЧП",
    "Stochastic PDE": "СУЧП",
    "Stochastic heat equation": "Стохастическое уравнение теплопроводности",
    "Stochastic reaction–diffusion": "Стохастическая реакция-диффузия",
    "Stochastic reaction-diffusion": "Стохастическая реакция-диффузия",
    "Stochastic phase-field": "Стохастическое фазовое поле",
    "Fluctuating hydrodynamics": "Флуктуационная гидродинамика",
    "Turbulence models": "Модели турбулентности",
    "Surface growth": "Рост поверхности",
    "Phase transformations": "Фазовые превращения",
    "Master Equations": "Мастер-уравнения",
    "Continuous-time Master Equation": "Мастер-уравнение непрерывного времени",
    "Chemical Master Equation — CME": "Химическое мастер-уравнение",
    "Chemical Master Equation - CME": "Химическое мастер-уравнение",
    "Quantum Master Equation": "Квантовое мастер-уравнение",
    "Markov jump processes": "Марковские скачкообразные процессы",
    "Fokker–Planck Equations": "Уравнение Фоккера-Планка",
    "Fokker-Planck Equations": "Уравнение Фоккера-Планка",
    "Probability density evolution": "Эволюция плотности вероятности",
    "Связь с SDE/Langevin": "Связь с СДУ/Ланжевена",
    "Markov Models": "Марковские модели",
    "Markov chains": "Марковские цепи",
    "Continuous-time Markov chains": "Марковские цепи непрерывного времени",
    "Monte Carlo Models": "Модели Монте-Карло",
    "Metropolis Monte Carlo": "Монте-Карло Метрополиса",
    "Kinetic Monte Carlo — kMC": "Кинетический Монте-Карло",
    "Kinetic Monte Carlo - kMC": "Кинетический Монте-Карло",
    "KMC": "kMC",
    "Gillespie SSA": "Алгоритм Gillespie",
    "Grand Canonical Monte Carlo — GCMC": "Монте-Карло GCMC",
    "Grand Canonical Monte Carlo - GCMC": "Монте-Карло GCMC",
    "Path / quantum Monte Carlo": "Путь/квантовый Монте-Карло",
    # ===== кинетические =====
    "КИНЕТИЧЕСКИЕ МОДЕЛИ": "Кинетические модели",
    "Boltzmann Equation": "Уравнение Больцмана",
    "Vlasov Equation": "Уравнение Власова",
    "Vlasov–Poisson": "Власова-Пуассона",
    "Vlasov-Poisson": "Власова-Пуассона",
    "Vlasov–Maxwell": "Власова-Максвелла",
    "Vlasov-Maxwell": "Власова-Максвелла",
    "BGK Equation": "Уравнение BGK",
    "Landau Equation": "Уравнение Ландау",
    "Fokker–Planck kinetic models": "Кинетические модели Фоккера-Планка",
    "Fokker-Planck kinetic models": "Кинетические модели Фоккера-Планка",
    "Radiative Transfer Equation": "Уравнение переноса излучения",
    "Phonon Boltzmann Transport Equation": "Уравнение Больцмана для фононов",
    "Electron Boltzmann Transport": "Электронный перенос Больцмана",
    "Rarefied gases": "Разреженные газы",
    "Plasma": "Плазма",
    "Semiconductor transport": "Перенос в полупроводниках",
    "Phonon heat transport": "Фононный теплоперенос",
    "Particle transport": "Перенос частиц",
    # ===== вариационные / спектральные =====
    "ВАРИАЦИОННЫЕ МОДЕЛИ": "Вариационные модели",
    "Variational Principles": "Вариационные принципы",
    "δJ[u] = 0": "δJ[u] = 0",
    "Least action": "Принцип наименьшего действия",
    "Minimum potential energy": "Минимум потенциальной энергии",
    "Minimum free energy": "Минимум свободной энергии",
    "Euler–Lagrange Equations": "Уравнения Эйлера-Лагранжа",
    "Euler-Lagrange Equations": "Уравнения Эйлера-Лагранжа",
    "Weak Formulations": "Слабые формулировки",
    "Galerkin formulation": "Формулировка Галёркина",
    "FEM basis": "Базис МКЭ",
    "Variational Inequalities": "Вариационные неравенства",
    "Obstacle problems": "Задачи о препятствии",
    "Energy Minimization": "Минимизация энергии",
    "Molecular geometry": "Молекулярная геометрия",
    "Phase-field": "Фазовое поле",
    "DFT": "ТФП",
    "Equilibrium structures": "Равновесные структуры",
    "СПЕКТРАЛЬНЫЕ ЗАДАЧИ": "Спектральные задачи",
    "Eigenvalue Problems": "Задачи на собственные значения",
    "Aφ = λφ": "Aφ = λφ",
    "Aφ = λBφ": "Aφ = λBφ",
    "Generalized Eigenvalue Problems": "Обобщённые задачи на собственные значения",
    "Modal Analysis": "Модальный анализ",
    "Kφ = ω²Mφ": "Kφ = ω²Mφ",
    "Stability Eigenproblems": "Спектральные задачи устойчивости",
    "Quantum Eigenproblems": "Квантовые спектральные задачи",
    "Hψ = Eψ": "Hψ = Eψ",
    "Применения": "Спектральные приложения",
    "Natural frequencies": "Собственные частоты",
    "Buckling": "Потеря устойчивости",
    "Waveguide modes": "Моды волноводов",
    "Quantum energy levels": "Квантовые уровни энергии",
    "Electronic structure": "Электронная структура",
    "Stability": "Устойчивость",
    # ===== оптимизация / обратные =====
    "ОПТИМИЗАЦИОННЫЕ МОДЕЛИ": "Оптимизационные модели",
    "Unconstrained Optimization": "Безусловная оптимизация",
    "min J(x)": "min J(x)",
    "Constrained Optimization": "Оптимизация с ограничениями",
    "Optimal Control": "Оптимальное управление",
    "Optimal control": "Оптимальное управление",
    "ODE-constrained": "ОДУ с ограничениями",
    "PDE-constrained": "УЧП с ограничениями",
    "Shape Optimization": "Оптимизация формы",
    "Topology Optimization": "Топологическая оптимизация",
    "Parameter Optimization": "Оптимизация параметров",
    "Inverse Design": "Обратное проектирование",
    "Inverse design": "Обратное проектирование",
    "ОБРАТНЫЕ И ИДЕНТИФИКАЦИОННЫЕ ЗАДАЧИ": "Обратные и идентификационные задачи",
    "Inverse Problems": "Обратные задачи",
    "Parameter Identification": "Идентификация параметров",
    "Parameter identification": "Идентификация параметров",
    "System Identification": "Идентификация систем",
    "Source Identification": "Идентификация источника",
    "Source identification": "Идентификация источника",
    "Boundary-condition identification": "Идентификация граничных условий",
    "Initial-condition reconstruction": "Восстановление начальных условий",
    "Initial-state reconstruction": "Восстановление начального состояния",
    "State Estimation": "Оценивание состояния",
    "Data Assimilation": "Ассимиляция данных",
    "Boundary reconstruction": "Восстановление границ",
    "Geometry identification": "Идентификация геометрии",
    "Constitutive-law identification": "Идентификация конститутивных законов",
    # ===== сети / агентные =====
    "СЕТЕВЫЕ / ГРАФОВЫЕ МОДЕЛИ": "Сетевые и графовые модели",
    "Graph Dynamical Systems": "Графовые динамические системы",
    "Graph Laplacian Models": "Модели графового лапласиана",
    "dx/dt = -Lx": "dx/dt = -Lx",
    "Reaction Networks": "Реакционные сети",
    "Electrical Networks": "Электрические сети",
    "Thermal Networks": "Тепловые сети",
    "Hydraulic Networks": "Гидравлические сети",
    "Pore Network Models": "Модели поровых сетей",
    "Molecular Graph Models": "Молекулярные графовые модели",
    "АГЕНТНЫЕ / ЧАСТИЧНЫЕ МОДЕЛИ": "Агентные и частичные модели",
    "Agent-Based Models — ABM": "Агентные модели",
    "Agent-Based Models - ABM": "Агентные модели",
    "Particle-Based Models": "Частичные модели",
    "Molecular Dynamics": "Молекулярная динамика",
    "Molecular Dynamics — MD": "Молекулярная динамика",
    "Molecular Dynamics - MD": "Молекулярная динамика",
    "Newtonian MD": "Ньютоновская МД",
    "Langevin MD": "МД Ланжевена",
    "Reactive MD": "Реактивная МД",
    "Discrete Element Method — DEM": "Метод дискретных элементов",
    "Discrete Element Method - DEM": "Метод дискретных элементов",
    "Smoothed Particle Hydrodynamics — SPH": "SPH",
    "Smoothed Particle Hydrodynamics - SPH": "SPH",
    "Brownian Dynamics": "Броуновская динамика",
    # ===== мультифизика / масштаб / гибриды =====
    "МУЛЬТИФИЗИЧЕСКИЕ МОДЕЛИ": "Мультифизические модели",
    "Thermo-mechanics": "Термомеханика",
    "Fluid–Structure Interaction — FSI": "Взаимодействие жидкость-конструкция",
    "Fluid-Structure Interaction - FSI": "Взаимодействие жидкость-конструкция",
    "Electro-thermal": "Электротермика",
    "Electro-mechanical": "Электромеханика",
    "Magneto-hydrodynamics — MHD": "МГД",
    "Magneto-hydrodynamics - MHD": "МГД",
    "Reaction–Diffusion": "Реакция-диффузия",
    "Reaction–Advection–Diffusion": "Реакция-адвекция-диффузия",
    "Thermo-Chemo-Mechanical": "Термохимомеханика",
    "Poromechanics": "Поромеханика",
    "Reactive flow": "Реактивное течение",
    "МУЛЬТИМАСШТАБНЫЕ МОДЕЛИ": "Мультимасштабные модели",
    "Electronic scale": "Электронный масштаб",
    "Schrödinger / DFT": "Шрёдингер / ТФП",
    "Schrodinger / DFT": "Шрёдингер / ТФП",
    "Atomistic scale": "Атомистический масштаб",
    "Mesoscale": "Мезомасштаб",
    "Coarse-grained MD": "Грубозернистая МД",
    "Continuum scale": "Континуальный масштаб",
    "FEM": "МКЭ",
    "CFD": "ВГД",
    "Continuum mechanics": "Механика континуума",
    "Coupled multiscale": "Связанные мультимасштабные модели",
    "QM/MM": "QM/MM",
    "MD ↔ continuum": "МД и континуум",
    "MD и continuum": "МД и континуум",
    "Micro ↔ macro homogenization": "Микро-макро гомогенизация",
    "Micro и macro homogenization": "Микро-макро гомогенизация",
    "ГИБРИДНЫЕ МОДЕЛИ": "Гибридные модели",
    "ODE + Algebraic → DAE": "ДАУ",
    "ODE + Algebraic -> DAE": "ДАУ",
    "PDE + Algebraic constraints": "УЧП с ограничениями",
    "ODE + Stochastic → SDE": "СДУ",
    "ODE + Stochastic -> SDE": "СДУ",
    "PDE + Stochastic → SPDE": "СУЧП",
    "PDE + Stochastic -> SPDE": "СУЧП",
    "Differential + Integral → IDE": "ИДУ",
    "Differential + Integral -> IDE": "ИДУ",
    "PDE + particle model": "Частичные УЧП",
    "Continuum + discrete": "Континуум и дискретная модель",
    "Physics + empirical model": "Физика и эмпирические модели",
    "Physics + ML": "Физика и ML",
    "Digital Twin / Hybrid Physics Model": "Цифровой двойник",
    "ODE / DAE": "ДАУ",
    "MD / DEM / SPH": "МД / DEM / SPH",
    # ===== тип постановки =====
    "По времени": "Классификация по времени",
    "Стационарная / steady-state": "Стационарная задача",
    "Квазистационарная": "Квазистационарная задача",
    "Нестационарная / transient": "Нестационарная задача",
    "Периодическая": "Периодическая задача",
    "Установившийся периодический режим": "Установившийся периодический режим",
    "По известным условиям": "Классификация по условиям",
    "Initial Value Problem — IVP": "Задача Коши",
    "Initial Value Problem - IVP": "Задача Коши",
    "задача Коши": "Задача Коши",
    "Boundary Value Problem — BVP": "Краевая задача",
    "Boundary Value Problem - BVP": "Краевая задача",
    "Dirichlet": "Граничные условия Дирихле",
    "Neumann": "Граничные условия Неймана",
    "Robin": "Граничные условия Робина",
    "Mixed": "Смешанные граничные условия",
    "Periodic BC": "Периодические граничные условия",
    "Initial-Boundary Value Problem — IBVP": "Начально-краевая задача",
    "Initial-Boundary Value Problem - IBVP": "Начально-краевая задача",
    "По направлению вывода": "Классификация по направлению",
    "Forward Problem": "Прямая задача",
    "параметры → состояние": "Параметры → состояние",
    "Inverse Problem": "Обратная задача",
    "наблюдения → параметры/источник/состояние": "Наблюдения → параметры/источник/состояние",
    "По искомой величине": "Классификация по искомой величине",
    "State problem": "Задача состояния",
    "По математической цели": "Классификация по цели",
    "Simulation": "Моделирование",
    "Prediction": "Прогнозирование",
    "Eigenvalue problem": "Задача на собственные значения",
    "Stability analysis": "Анализ устойчивости",
    "Bifurcation analysis": "Анализ бифуркаций",
    "Optimization": "Оптимизация",
    "По определённости": "Классификация по определённости",
    "Deterministic": "Детерминированная постановка",
    "Stochastic": "Стохастическая постановка",
    "Uncertain parameters": "Неопределённые параметры",
    "Robust": "Робастная постановка",
    "Probabilistic": "Вероятностная постановка",
    # ===== представление =====
    "Lumped / сосредоточенная": "Сосредоточенная модель",
    "Continuum / сплошная среда": "Сплошная среда",
    "Distribution / распределение частиц": "Распределение частиц",
    "Kinetic equations": "Кинетические уравнения",
    "Particle / частицы": "Частичная модель",
    "Discrete lattice": "Дискретная решётка",
    "Cellular Automata / Ising / KMC": "Клеточные автоматы / Изинг / kMC",
    "Network": "Сетевая модель",
    "Graph / network equations": "Графовые и сетевые уравнения",
    "Probabilistic state": "Вероятностное состояние",
    "Master / Fokker–Planck": "Мастер-уравнение / Фоккера-Планка",
    "Master / Fokker-Planck": "Мастер-уравнение / Фоккера-Планка",
    "Quantum state": "Квантовое состояние",
    "Schrödinger / density matrix / DFT": "Шрёдингер / матрица плотности / ТФП",
    "Itô SDE": "СДУ Ито",
    "Ito SDE": "СДУ Ито",
    "Linear": "Линейные",
    "Nonlinear": "Нелинейные",
    "g ≥ 0": "g ≥ 0",
    "g >= 0": "g ≥ 0",
    "λ ≥ 0": "λ ≥ 0",
    "λ >= 0": "λ ≥ 0",
    "h(x) ≤ 0": "h(x) ≤ 0",
    "h(x) <= 0": "h(x) ≤ 0",
    # ===== section headers (already Russian) =====
    "НЕПРЕРЫВНЫЕ МОДЕЛИ": "Непрерывные модели",
    "Процессы": "Процессы",
    "Процессы:": "Процессы",
}

EXTRA_MODELS: dict[str, str] = {
    "Schrödinger equation": "Уравнение Шрёдингера",
    "Time-dependent Schrödinger equation": "Нестационарное уравнение Шрёдингера",
    "Nonlinear Schrödinger equation": "Нелинейное уравнение Шрёдингера",
    "Gross-Pitaevskii equation": "Уравнение Гросса-Питаевского",
    "Dirac equation": "Уравнение Дирака",
    "Klein-Gordon equation": "Уравнение Кlein-Gordon",
    "Pauli equation": "Уравнение Паули",
    "Burgers equation": "Уравнение Бurgers",
    "Korteweg-de Vries equation": "Уравнение Кортевега-де Фриза",
    "KdV equation": "Уравнение KdV",
    "Modified KdV equation": "Модифицированное уравнение KdV",
    "Sine-Gordon equation": "Уравнение sine-Gordon",
    "Fisher-KPP equation": "Уравнение Fisher-KPP",
    "KPP equation": "Уравнение KPP",
    "Allen-Cahn equation": "Уравнение Allen-Cahn",
    "Cahn-Hilliard equation": "Уравнение Cahn-Hilliard",
    "Ginzburg-Landau equation": "Уравнение Ginzburg-Landau",
    "Swift-Hohenberg equation": "Уравнение Swift-Hohenberg",
    "Kuramoto-Sivashinsky equation": "Уравнение Kuramoto-Sivashinsky",
    "Gray-Scott model": "Модель Gray-Scott",
    "Lotka-Volterra equations": "Уравнения Лотки-Вольтерра",
    "SIR model": "Модель SIR",
    "SEIR model": "Модель SEIR",
    "Compartment models": "Компартментные модели",
    "Black-Scholes equation": "Уравнение Black-Scholes",
    "Heston model": "Модель Heston",
    "Merton model": "Модель Merton",
    "Riccati equation": "Уравнение Riccati",
    "Bernoulli equation": "Уравнение Bernoulli",
    "Duffing oscillator": "Осциллятор Duffing",
    "Van der Pol oscillator": "Осциллятор Van der Pol",
    "Lorenz system": "Система Lorenz",
    "Rössler system": "Система Rössler",
    "Pendulum equation": "Уравнение маятника",
    "Double pendulum": "Двойной маятник",
    "Fitzhugh-Nagumo model": "Модель Fitzhugh-Nagumo",
    "Hodgkin-Huxley model": "Модель Hodgkin-Huxley",
    "Stefan problem": "Задача Stefan",
    "Stefan-Maxwell equations": "Уравнения Stefan-Maxwell",
    "Muskat problem": "Задача Muskat",
    "Richards equation": "Уравнение Richards",
    "Darcy law": "Закон Darcy",
    "Darcy-Brinkman equation": "Уравнение Darcy-Brinkman",
    "Brinkman equation": "Уравнение Brinkman",
    "Forchheimer equation": "Уравнение Forchheimer",
    "Biot consolidation": "Кonsolidation Biot",
    "Biot poroelasticity": "Пороупругость Biot",
    "Terzaghi consolidation": "Кonsolidation Terzaghi",
    "Cam-clay model": "Модель Cam-clay",
    "Drucker-Prager model": "Модель Drucker-Prager",
    "Mohr-Coulomb model": "Модель Mohr-Coulomb",
    "J2 plasticity": "J2-пластичность",
    "Von Mises plasticity": "Пластичность von Mises",
    "Arrhenius kinetics": "Кинетика Arrhenius",
    "Michaelis-Menten kinetics": "Кинетика Michaelis-Menten",
    "Langmuir isotherm": "Изотерма Langmuir",
    "BET isotherm": "Изотерма BET",
    "Freundlich isotherm": "Изотерма Freundlich",
    "Nernst-Planck equation": "Уравнение Nernst-Planck",
    "Poisson-Nernst-Planck system": "Система Poisson-Nernst-Planck",
    "Smoluchowski equation": "Уравнение Smoluchowski",
    "Fokker-Planck equation": "Уравнение Fokker-Planck",
    "Langevin dynamics": "Динамика Langevin",
    "Reynolds equation": "Уравнение Reynolds",
    "Prandtl boundary layer": "Пограничный слой Prandtl",
    "Blasius equation": "Уравнение Blasius",
    "Falkner-Skan equation": "Уравнение Falkner-Skan",
    "Rayleigh-Bénard convection": "Конвекция Rayleigh-Bénard",
    "Marangoni convection": "Конвекция Marangoni",
    "Bénard-Marangoni problem": "Задача Bénard-Marangoni",
    "Couette flow": "Течение Couette",
    "Poiseuille flow": "Течение Poiseuille",
    "Stokes flow": "Течение Stokes",
    "Oseen approximation": "Приближение Oseen",
    "Potential flow model": "Модель потенциального течения",
    "Shallow water equations": "Мелководные уравнения",
    "Saint-Venant equations": "Уравнения Saint-Venant",
    "Boussinesq approximation": "Приближение Boussinesq",
    "Anelastic approximation": "Анэластическое приближение",
    "Helmholtz equation": "Уравнение Helmholtz",
    "Biharmonic equation": "Бигармоническое уравнение",
    "Monge-Ampère equation": "Уравнение Monge-Ampère",
    "Eikonal equation": "Eikonal-уравнение",
    "Optimal transport problem": "Задача оптимального переноса",
    "Wasserstein gradient flow": "Wasserstein-поток",
    "Peridynamics": "Peridynamics",
    "Phase-field crystal model": "Модель phase-field crystal",
    "Shallow ice approximation": "Приближение shallow ice",
    "Glacier flow model": "Модель ледникового течения",
    "Ice sheet model": "Модель ледяного щита",
    "k-epsilon turbulence model": "Модель турбулентности k-epsilon",
    "k-omega turbulence model": "Модель турбулентности k-omega",
    "Spalart-Allmaras model": "Модель Spalart-Allmaras",
    "Smagorinsky model": "Модель Smagorinsky",
    "Large Eddy Simulation": "Large Eddy Simulation",
    "Direct Numerical Simulation": "Direct Numerical Simulation",
    "RANS models": "RANS-модели",
    "Reynolds-averaged Navier-Stokes": "Reynolds-averaged Navier-Stokes",
    "Magnetostatics": "Магнитостатика",
    "Magnetostriction model": "Модель магнитостriction",
    "Piezoelectricity model": "Пьезоэlectricity",
    "Landau-Lifshitz-Gilbert equation": "Уравнение Landau-Lifshitz-Gilbert",
    "Maxwell-Garnett model": "Модель Maxwell-Garnett",
    "Bruggeman effective medium": "Эффективная среда Bruggeman",
    "Clausius-Mossotti relation": "Соотношение Clausius-Mossotti",
    "Heat pipe model": "Модель тепловой трубы",
    "Stefan-Boltzmann law": "Закон Stefan-Boltzmann",
    "Rosseland approximation": "Приближение Rosseland",
    "P1 approximation": "P1-приближение",
    "SN transport equation": "SN-перенос",
    "PN transport equation": "PN-перенос",
    "Discrete ordinates method": "Метод discrete ordinates",
    "Multigroup diffusion": "Мультигрупповая диффузия",
    "Neutron diffusion equation": "Уравнение нейтронной диффузии",
    "Neutron transport equation": "Уравнение нейтронного переноса",
    "Point kinetics equations": "Уравнения point kinetics",
    "Bateman equations": "Уравнения Bateman",
    "Radioactive decay chains": "Цепочки радиоактивного распада",
    "Burnup model": "Модель burnup",
    "Xenon dynamics model": "Динамика xenon",
    "Windkessel model": "Модель Windkessel",
    "Hemodynamics model": "Модель гемодинамики",
    "Coronary flow model": "Модель коронарного тока",
    "Perfusion model": "Модель перфузии",
    "Tumor growth model": "Модель роста опухоли",
    "Gompertz model": "Модель Gompertz",
    "Avascular tumor model": "Модель безсосудистой опухоли",
    "Angiogenesis model": "Модель ангиогенеза",
    "Keller-Segel model": "Модель Keller-Segel",
    "Chemotaxis model": "Модель хemotaxis",
    "Volume of fluid method": "Метод Volume of Fluid",
    "Level set method": "Level-set метод",
    "Front tracking method": "Метод front tracking",
    "Immersed boundary method": "Immersed boundary method",
    "Arbitrary Lagrangian-Eulerian method": "ALE-метод",
    "Turing pattern model": "Модель Turing",
    "Brusselator model": "Модель Brusselator",
    "Oregonator model": "Модель Oregonator",
    "Belousov-Zhabotinsky reaction": "Реакция Belousov-Zhabotinsky",
    "Schnakenberg model": "Модель Schnakenberg",
    "Thomas model": "Модель Thomas",
    "Multiphase flow model": "Модель многофазного течения",
    "Drift-flux model": "Drift-flux модель",
    "Two-fluid model": "Двухфлюидная модель",
    "Euler-Euler model": "Модель Euler-Euler",
    "Euler-Lagrange model": "Модель Euler-Lagrange",
    "Population balance equation": "Уравнение population balance",
    "Coagulation-fragmentation equation": "Уравнение коagulation-fragmentation",
    "Smoluchowski coagulation equation": "Уравнение коagulation Smoluchowski",
    "Liouville equation": "Уравнение Liouville",
    "Liouville-Boltzmann equation": "Уравнение Liouville-Boltzmann",
    "Chapman-Enskog expansion": "Разложение Chapman-Enskog",
    "Grad moment equations": "Grad moment equations",
    "Burnett equations": "Уравнения Burnett",
    "Super-Burnett equations": "Уравнения Super-Burnett",
    "Grad 13-moment equations": "Grad 13-moment equations",
    "ES-BGK model": "ES-BGK модель",
    "Shakhov model": "Shakhov модель",
    "Discrete velocity model": "Discrete velocity model",
    "Quasi-geostrophic equations": "Quasi-geostrophic equations",
    "Primitive equations": "Primitive equations",
    "Navier-Stokes-alpha model": "Navier-Stokes-alpha",
    "Clark-alpha model": "Clark-alpha model",
    "Leray-alpha model": "Leray-alpha model",
    "Magnetohydrostatics": "Magnetohydrostatics",
    "Hall-MHD equations": "Hall-MHD equations",
    "Resistive MHD equations": "Resistive MHD equations",
    "Ideal MHD equations": "Ideal MHD equations",
    "Double adiabatic MHD": "Double adiabatic MHD",
    "Radiation MHD": "Radiation MHD",
    "Thermoelasticity model": "Thermoelasticity",
    "Thermodiffusion model": "Thermodiffusion",
    "Soret effect model": "Soret effect model",
    "Dufour effect model": "Dufour effect model",
    "Maxwell-Stefan diffusion": "Maxwell-Stefan diffusion",
    "Darken equation": "Darken equation",
    "Onsager reciprocal relations": "Onsager reciprocal relations",
    "Flory-Huggins theory": "Flory-Huggins theory",
    "Rouse model": "Rouse model",
    "Zimm model": "Zimm model",
    "Wormlike chain model": "Wormlike chain model",
    "Freely jointed chain model": "Freely jointed chain model",
    "Bead-spring model": "Bead-spring model",
    "DPD model": "Dissipative particle dynamics",
    "EAM potential model": "EAM potential model",
    "Tersoff potential model": "Tersoff potential model",
    "Stillinger-Weber potential": "Stillinger-Weber potential",
    "Embedded atom method": "Embedded atom method",
    "ReaxFF model": "ReaxFF model",
    "CHARMM force field": "CHARMM force field",
    "AMBER force field": "AMBER force field",
    "OPLS force field": "OPLS force field",
    "GROMOS force field": "GROMOS force field",
    "Coarse-grained Martini model": "Martini coarse-grained model",
    "MARTINI force field": "MARTINI force field",
    "Dissipative hydrodynamics": "Dissipative hydrodynamics",
    "Second-order fluid model": "Second-order fluid model",
    "Oldroyd-B model": "Oldroyd-B model",
    "Maxwell fluid model": "Maxwell fluid model",
    "Kelvin-Voigt model": "Kelvin-Voigt model",
    "Standard linear solid model": "Standard linear solid model",
    "Zener model": "Zener model",
    "Burgers model": "Burgers model",
    "Power-law fluid model": "Power-law fluid model",
    "Herschel-Bulkley model": "Herschel-Bulkley model",
    "Bingham plastic model": "Bingham plastic model",
    "Carreau model": "Carreau model",
    "Cross model": "Cross model",
    "Casson model": "Casson model",
    "Thixotropic fluid model": "Thixotropic fluid model",
    "Yield-stress fluid model": "Yield-stress fluid model",
    "Non-Newtonian fluid models": "Non-Newtonian fluid models",
    "Blood flow model": "Blood flow model",
    "Carreau-Yasuda model": "Carreau-Yasuda model",
    "Generalized Newtonian fluid": "Generalized Newtonian fluid",
    "Ericksen-Leslie theory": "Ericksen-Leslie theory",
    "Liquid crystal model": "Liquid crystal model",
    "Q-tensor model": "Q-tensor model",
    "Beris-Edwards model": "Beris-Edwards model",
    "Doi-Edwards model": "Doi-Edwards model",
    "Rouse-Zimm model": "Rouse-Zimm model",
    "FENE-P model": "FENE-P model",
    "FENE dumbbell model": "FENE dumbbell model",
    "Giesekus model": "Giesekus model",
    "Phan-Thien-Tanner model": "Phan-Thien-Tanner model",
    "Leonov model": "Leonov model",
    "White-Metzner model": "White-Metzner model",
    "Bird-Carreau model": "Bird-Carreau model",
    "Johnson-Segalman model": "Johnson-Segalman model",
    "Diffusion-reaction tumor model": "Diffusion-reaction tumor model",
    "Mechano-biological growth model": "Mechano-biological growth model",
    "Bone remodeling model": "Bone remodeling model",
    "Wolff law model": "Wolff law model",
    "Continuum damage mechanics": "Continuum damage mechanics",
    "Gurson model": "Gurson model",
    "GTN model": "GTN model",
    "Cohesive zone model": "Cohesive zone model",
    "Phase-field fracture model": "Phase-field fracture model",
    "Griffith fracture criterion": "Griffith fracture criterion",
    "Linear elastic fracture mechanics": "Linear elastic fracture mechanics",
    "J-integral model": "J-integral model",
    "Paris law": "Paris law",
    "Fatigue crack growth model": "Fatigue crack growth model",
    "Creep-fatigue model": "Creep-fatigue model",
    "Chaboche model": "Chaboche model",
    "Armstrong-Frederick model": "Armstrong-Frederick model",
    "Bauschinger effect model": "Bauschinger effect model",
    "Crystal plasticity model": "Crystal plasticity model",
    "Taylor hardening model": "Taylor hardening model",
    "Voce hardening law": "Voce hardening law",
    "Swift hardening law": "Swift hardening law",
    "Ludwik hardening law": "Ludwik hardening law",
    "Hollomon law": "Hollomon law",
    "Ramberg-Osgood model": "Ramberg-Osgood model",
    "Neuber rule model": "Neuber rule model",
    "Shakedown theory model": "Shakedown theory model",
    "Limit analysis model": "Limit analysis model",
    "Sliding mode control model": "Sliding mode control model",
    "Hamilton-Jacobi-Bellman equation": "Hamilton-Jacobi-Bellman equation",
    "Riccati optimal control": "Riccati optimal control",
    "Linear-quadratic regulator": "Linear-quadratic regulator",
    "Kalman filter model": "Kalman filter model",
    "Extended Kalman filter": "Extended Kalman filter",
    "Ensemble Kalman filter": "Ensemble Kalman filter",
    "Particle filter model": "Particle filter model",
    "Bayesian inverse problem": "Bayesian inverse problem",
    "Tikhonov regularization": "Tikhonov regularization",
    "Total variation regularization": "Total variation regularization",
    "Compressed sensing model": "Compressed sensing model",
    "POD reduced-order model": "POD reduced-order model",
    "Reduced basis method": "Reduced basis method",
    "Proper generalized decomposition": "Proper generalized decomposition",
    "Dynamic mode decomposition": "Dynamic mode decomposition",
    "Koopman operator model": "Koopman operator model",
    "Physics-informed neural networks": "Physics-informed neural networks",
    "DeepONet operator model": "DeepONet operator model",
    "Fourier neural operator": "Fourier neural operator",
    "Graph neural network model": "Graph neural network model",
    "Surrogate modeling": "Surrogate modeling",
    "Response surface model": "Response surface model",
    "Kriging model": "Kriging model",
    "Gaussian process regression": "Gaussian process regression",
    "Polynomial chaos expansion": "Polynomial chaos expansion",
    "Stochastic collocation method": "Stochastic collocation method",
    "Multifidelity modeling": "Multifidelity modeling",
    "Digital twin model": "Digital twin model",
    "Hybrid physics-ML model": "Hybrid physics-ML model",
}


def _fold(text: str) -> str:
    text = text.translate(str.maketrans({"–": "-", "—": "-", "−": "-"}))
    text = text.replace("→", "->").replace("↔", "<->")
    text = text.replace("≥", ">=").replace("≤", "<=")
    text = re.sub(r"\s*<=\s*", "<=", text)
    text = re.sub(r"\s*>=\s*", ">=", text)
    return text.casefold().strip()


def _validate(entries: dict[str, str]) -> None:
    folded: dict[str, str] = {}
    for key, value in entries.items():
        f = _fold(key)
        if f in folded and folded[f] != value:
            raise ValueError(f"conflict for {key!r}: {folded[f]!r} vs {value!r}")
        folded[f] = value


def main() -> None:
    all_entries = {**LABEL_ENTRIES, **EXTRA_MODELS, **ADDITIONAL_MODELS}
    deduped: dict[str, tuple[str, str]] = {}
    for key, value in all_entries.items():
        folded = _fold(key)
        if folded not in deduped:
            deduped[folded] = (key, value)
    final_entries = {orig: val for orig, val in deduped.values()}
    print(f"Entries: {len(all_entries)} raw, {len(final_entries)} unique folded keys")

    lines = [
        '"""Прямой словарь переводов: метка -> русское название (без преобразований)."""',
        "",
        "from __future__ import annotations",
        "",
        "import re",
        "",
        "_DASHES = str.maketrans({'–': '-', '—': '-', '−': '-'})",
        "",
        "",
        "def normalize_dashes(text: str) -> str:",
        "    return text.translate(_DASHES)",
        "",
        "",
        "def fold(text: str) -> str:",
        "    text = normalize_dashes(text)",
        "    text = text.replace('→', '->').replace('↔', '<->')",
        "    text = text.replace('≥', '>=').replace('≤', '<=')",
        "    text = re.sub(r'\\s*<=\\s*', '<=', text)",
        "    text = re.sub(r'\\s*>=\\s*', '>=', text)",
        "    return text.casefold().strip()",
        "",
        "",
        "def _build_label_dict(entries: dict[str, str]) -> dict[str, str]:",
        "    out: dict[str, str] = {}",
        "    for key, value in entries.items():",
        "        out[fold(key)] = value",
        "    if len(out) != len(entries):",
        "        raise ValueError('LABEL_RU: duplicate folded keys')",
        "    return out",
        "",
        "",
        "_LABEL_ENTRIES: dict[str, str] = {",
    ]

    for key in sorted(final_entries, key=lambda s: (_fold(s), s)):
        val = final_entries[key]
        lines.append(f"    {key!r}: {val!r},")

    lines.extend([
        "}",
        "",
        "LABEL_RU = _build_label_dict(_LABEL_ENTRIES)",
        "LABEL_ENTRIES = _LABEL_ENTRIES",
        "",
        "",
        "def translate_label(label: str) -> str | None:",
        '    """Прямой перевод по ключу; None если нет в словаре."""',
        "    return LABEL_RU.get(fold(label))",
        "",
        "",
        "def translation_stats() -> dict[str, int]:",
        "    return {'labels': len(LABEL_RU)}",
        "",
    ])

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} with {len(final_entries)} entries")


if __name__ == "__main__":
    main()
